Removed docker hub runid tag
mangata-finance/mangata-node pull request #119
Opened 2021-08-26 13:53 UTC by omaksi

2021-09-14 15:42 UTC, gleb-urvanov reviewed
Any reason why it causes the tests to fail?

2021-09-14 15:53 UTC, goncer commented
Ruinas is used to archive the generated image. I can fix it by replacing it
by sha.

On Tue, 14 Sep 2021, 17:42 gleb-urvanov, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Any reason why it causes the tests to fail?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/mangata-finance/mangata-node/pull/119#pullrequestreview-754124792>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADTQEOFRJLOWMBE4L7KBXHTUB5UOJANCNFSM5C3NIEXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-15 06:29 UTC, goncer requested changes

2021-09-15 09:03 UTC, goncer approved these changes

2021-09-22 12:10 UTC, merged