Feature/liquidity mining rewards
mangata-finance/mangata-node pull request #178
Opened 2022-01-20 10:21 UTC by stanieltron

added functions for  minting liquidity rewards

NEW RPC:
 pub fn calculate_rewards_amount(
		user: AccountIdOf<T>,
		liquidity_asset_id: TokenId,
		block_number: u32,
	) -> Result<(Balance, i128) //(total earned, already claimed)
	
NEW EXTRINSIC:
fn claim_rewards(
		sender: AccountId,
		liquidity_token_id: Self::CurrencyId,
		amount: Self::Balance,
	)

2022-01-20 12:18 UTC, mateuszaaa requested changes
few minor comments

2022-01-20 12:18 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +		StorageMap<_, Blake2_256, TokenId, Option<Balance>, ValueQuery>;
not sure why keys are Option? Is there any use case for that ?

2022-01-20 12:18 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +				Self::liquidity_mining_pool_claimed(&liquidity_asset_id).unwrap();
again if you change the storage type to non-Option you wouldnt have to unwrap here ;)

2022-01-20 12:18 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +		let current_time = block_number / 1000;
please avoid magic numbers and use  named  const variable instead of  `1000`

2022-01-20 12:18 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +		// let (last_checkpoint,cummulative_work_in_last_checkpoint,missing_at_last_checkpoint,  )= UsersMinting::<T>::get((&user, &liquidity_asset_id)).unwrap();
remove comment

2022-01-20 12:18 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +		Ok(pool_work)
```
Self::calculate_work(
			liquidity_assets_amount,
			current_time,
			last_checkpoint,
			cummulative_work_in_last_checkpoint,
			missing_at_last_checkpoint,
		)
```
should work, return types are compatible

2022-01-21 19:56 UTC, iStrike7 reviewed
Why are we using i128 in some places?
The libm library we are using, how are its performance characteristics? Does it solve our problems?
In some places we are using U256 containers to multiply more than 2 numbers, is that safe? Are the computations resilient to saturation?

2022-01-24 09:38 UTC, stanieltron commented
> Why are we using i128 in some places? The libm library we are using, how are its performance characteristics? Does it solve our problems? In some places we are using U256 containers to multiply more than 2 numbers, is that safe? Are the computations resilient to saturation?

-i128 is used because this numbers can go to negative values (wanted in this implementation)
-libm, not sure about performance, prob will be reworked for different calculation, where libm will not be necessary
-U256 is used to prevent overflow, not yet tested if it is enough for every case

2022-02-03 18:04 UTC, mateuszaaa approved these changes
lgtm

2022-02-03 18:05 UTC, merged