Feature: MGX-55 Helm chart and `dev` environment deployment workflow
mangata-finance/mangata-node pull request #341
Opened 2022-10-27 19:41 UTC by tenequm

https://mangatafinance.atlassian.net/browse/MGX-55

2022-11-10 15:21 UTC, vanderian approved these changes

2022-11-10 18:45 UTC, majusko requested changes

2022-11-10 18:45 UTC, majusko commented on .github/workflows/deploy.yml
> +      - name: Create a GitHub Deployment
One thing I would refactor is to move the steps into separate reusable actions. This way, we will be able to create our reusable actions across all repositories in a single repository. I think it's better to do this now, and we can decide on moving them to a separate repository later.

Check this repo for inspiration: https://github.com/mangata-finance/mangata-stash/tree/main/.github/actions

2022-11-11 11:05 UTC, majusko approved these changes

2022-11-14 10:00 UTC, merged