Multiswaps
mangata-finance/mangata-node pull request #406
Opened 2023-01-23 07:31 UTC by iStrike7

2023-02-08 10:39 UTC, majusko requested changes

2023-02-08 10:39 UTC, majusko commented on pallets/xyk/src/lib.rs
> +			frame_support::storage::with_storage_layer(|| -> Result<Balance, DispatchError> {
code style comment:

Let's move the whole functionality of `let res_multiswap =` calculation to a separate method.

2023-02-08 10:39 UTC, majusko commented on pallets/xyk/src/lib.rs
> +		let res_multiswap =
code style comment:

Let's move the whole functionality of let res_multiswap = calculation to a separate method.

2023-02-08 10:53 UTC, mateuszaaa requested changes

2023-02-08 10:53 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +
```
		ensure!(swap_token_list.len() > 2_usize, Error::<T>::MultiswapShouldBeAtleastTwoHops);
		// Unwraps are fine due to above ensure
		let sold_asset_id = *swap_token_list.get(0).unwrap();
		let bought_asset_id = *swap_token_list.get(1).unwrap();
    ```
    i would rather use below to completly get rid of unwraps

```
		let sold_asset_id = *swap_token_list.get(0).ok_or(Error::<T>::MultiswapShouldBeAtleastTwoHops)?
		let bought_asset_id = *swap_token_list.get(1).ok_or(Error::<T>::MultiswapShouldBeAtleastTwoHops)?;
```

2023-02-08 10:53 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +
if you collect directly to hashset, you can avoide few unecescary allocations, and separate dedup call

2023-02-08 10:53 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +			pair_sold_assets.into_iter().zip(pair_bought_assets.into_iter()).collect();
remove(0) on vec is not very efficient, consider using 
```
		let atomic_pairs: Vec<(TokenId, TokenId)> =
			swap_token_list.iter().skip(1).zip(swap_token_list.iter()).collect();

```
instead

2023-02-08 10:53 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +					pair_sold_assets.into_iter().zip(pair_bought_assets.into_iter()).collect();
remove(0) on vec is not very efficient, consider using 
```
		let atomic_pairs: Vec<(TokenId, TokenId)> =
			swap_token_list.iter().skip(1).zip(swap_token_list.iter()).collect();

```
instead

2023-02-08 10:53 UTC, majusko requested changes

2023-02-08 10:53 UTC, majusko commented on pallets/xyk/src/lib.rs
> +		#[pallet::weight(<<T as Config>::WeightInfo>::multiswap_sell_asset(swap_token_list.len() as u32))]
Missing docs:

Please add the docs to all `pub fn` for our docs autogeneration, the same as it is done in the Bootstrap pallet.

2023-02-08 10:55 UTC, mateuszaaa requested changes
please assign full-benchmarks label so ci can output new benchmarks for newly added functions

2023-02-09 10:25 UTC, majusko approved these changes
🙌 nice work!

2023-02-10 06:46 UTC, mateuszaaa approved these changes
lgmt, lets wait for ci and merge it

2023-02-10 08:40 UTC, mateuszaaa approved these changes
lgtm

2023-02-10 08:42 UTC, merged