WIP Bugfix/liq tokens MGX-434
mangata-finance/mangata-node pull request #505
Opened 2023-05-31 10:50 UTC by majusko

2023-05-31 11:52 UTC, mateuszaaa requested changes

2023-05-31 11:52 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +			.ok_or_else(|| Error::<T>::UnexpectedFailure.into())
you can use below to avoid unnecescary function call
```
			.ok_or(Error::<T>::UnexpectedFailure)
```

2023-05-31 11:52 UTC, mateuszaaa commented on pallets/xyk/src/lib.rs
> +		).ok_or(Error::<T>::UnexpectedFailure)?;
it seems that in case of total_liquidity_issuance == 0 it will evalute to 0 :thinking: ?

2023-05-31 11:54 UTC, mateuszaaa requested changes
consider addint UT for scenario where pool is fully drained and then someone comes to "recreate it"

2023-05-31 12:42 UTC, majusko commented on pallets/xyk/src/lib.rs
> +			ensure!(!first_asset_reserve.is_zero(), Error::<T>::DivisionByZero);
True, but it was there before like this. Should I change it to something else since updating this part?

2023-08-23 12:13 UTC, mateuszaaa approved these changes

2023-08-23 13:00 UTC, mateuszaaa submitted a review, later dismissed
lgtm

2023-09-11 13:09 UTC, majusko commented on pallets/xyk/src/tests.rs
> +			vec![1, 2, 3, 4, 5],
This was probably an old bug in our tests that went unnoticed until this added validation

2023-09-12 07:11 UTC, mateuszaaa submitted a review, later dismissed
lgtm

2023-09-20 12:51 UTC, merged