Storage migration asset registry
mangata-finance/mangata-node pull request #539
Opened 2023-07-25 13:03 UTC by devdanco

2023-07-25 13:55 UTC, vanderian submitted a review, later dismissed

2023-07-26 16:49 UTC, mateuszaaa requested changes

2023-07-26 16:49 UTC, mateuszaaa commented on runtime/mangata-kusama/src/migration.rs
> +				let issuance = orml_tokens::Pallet::<Runtime>::total_issuance(_key);
its either prefixed with `_` and unused, or not prefixed ;)

2023-07-26 16:49 UTC, mateuszaaa commented on runtime/mangata-kusama/src/migration.rs
> +				if issuance.is_zero() && name.map_or(false, |n| n.starts_with("Liquidity")) {
you should rather use XYK::LiquidityAssets to check if given asset is liquidity asset

2023-07-26 16:49 UTC, mateuszaaa commented on runtime/mangata-kusama/src/migration.rs
> +		Ok(Vec::new())
please check if there are any assets that require migration, so we can make sure that this migration will start failing on ci after runtime upgrade and we will not forget to remove it ;)

2023-07-26 16:49 UTC, mateuszaaa commented on runtime/mangata-kusama/src/migration.rs
> +			if name.map_or(false, |n| n.starts_with("Liquidity")) {
please use XYK to check whether asset is liquidity token or not

2023-07-26 16:49 UTC, mateuszaaa commented on runtime/mangata-rococo/src/migration.rs
> +pub struct AssetRegistryMigration;
[optional] ideally AssetRegistryMigration should be put in `common_runtime`. Then you will have no access to `Runtime` directly but you can make AssetRegistryMigration generic over Runtime with proper bounds

https://github.com/mangata-finance/mangata-node/blob/3a395521bf47d15d6eeb669c36df1e1c7a8d6e8a/runtime/common/src/lib.rs#L457-L468

2023-07-31 07:35 UTC, mateuszaaa approved these changes

2023-07-31 07:36 UTC, merged