[MGX-632] 3rdparty rewards #593
mangata-finance/mangata-node pull request #643
Opened 2023-11-13 08:17 UTC by mateuszaaa

2023-11-14 12:03 UTC, vanderian approved these changes

2023-11-14 12:03 UTC, vanderian commented on runtime/mangata-kusama/Cargo.toml
> +	"pallet-balances/std",
what are we using `pallet-balances` for

2023-11-15 07:19 UTC, mateuszaaa commented on pallets/proof-of-stake/src/lib.rs
> +			>>::activate_liquidity(sender, liquidity_token_id, amount, use_balance_from)
yep!

2023-11-15 07:19 UTC, mateuszaaa commented on pallets/proof-of-stake/src/reward_info.rs
> +}
its used now :)

2023-11-15 07:20 UTC, mateuszaaa commented on runtime/mangata-kusama/Cargo.toml
> +	"pallet-balances/std",
removedd

2023-11-15 13:39 UTC, majusko requested changes

2023-11-15 13:39 UTC, majusko commented on pallets/parachain-staking/src/benchmarks.rs
> +	// active_session_change {
Why did we comment out this section?

2023-11-15 13:43 UTC, majusko requested changes

2023-11-15 13:43 UTC, majusko commented on pallets/proof-of-stake/rpc/src/lib.rs
> +	fn calculate_native_rewards_amount(
Collect all breaking changes into the Jira ticket pls

2023-11-15 13:43 UTC, majusko commented on pallets/proof-of-stake/rpc/src/lib.rs
> +#[rpc(client, server)]
If possible, please add documentation to API, describing what it is doing and what is the expected result.

2023-11-20 05:21 UTC, mateuszaaa commented on pallets/parachain-staking/src/benchmarks.rs
> +	// active_session_change {
just for testing, reverted

2023-11-27 09:26 UTC, vanderian approved these changes

2023-11-27 14:35 UTC, majusko approved these changes

2023-11-27 14:38 UTC, merged