Mangata solo develop
mangata-finance/mangata-node pull request #697
Opened 2024-02-22 09:37 UTC by iStrike7

2024-02-22 09:57 UTC, mateuszaaa requested changes

2024-02-22 09:57 UTC, mateuszaaa commented on rollup/runtime/integration-test/src/xyk.rs
> +
nice! are these new tests or they were moved from somewhere

2024-02-22 09:57 UTC, mateuszaaa commented on rollup/node/src/command.rs
> +			"" | "rollup-local" => Box::new(chain_spec::rollup_local_config()),
could you make sure that this config is also available
https://github.com/mangata-finance/mangata-node/pull/689

2024-02-22 10:31 UTC, majusko submitted a review, later dismissed

2024-02-22 10:36 UTC, iStrike7 commented on rollup/runtime/integration-test/src/xyk.rs
> +
These integration tests were copied from our current runtime integration tests

2024-02-22 10:38 UTC, iStrike7 commented on rollup/node/src/command.rs
> +			"" | "rollup-local" => Box::new(chain_spec::rollup_local_config()),
This PR/branch was created from current develop so it has no rolldown stuff and hence no concept of sequencers. When we switch over to "main-ing" the solochain, I can port the rolldown stuff to it.

2024-04-29 07:24 UTC, mateuszaaa commented
already delivered

2024-04-29 07:24 UTC, closed without merging