Eth rollup develop solo acc20
mangata-finance/mangata-node pull request #716
Opened 2024-03-20 20:03 UTC by iStrike7

2024-03-21 11:17 UTC, goncer approved these changes

2024-03-21 11:17 UTC, goncer commented on rollup/runtime/src/runtime_config.rs
> +					// TODO AccountId20
this //TODO still apply?

2024-03-21 22:43 UTC, mateuszaaa requested changes
LGTM but let me check how it affects metamask signing

2024-03-22 12:30 UTC, mateuszaaa requested changes
lgtm

2024-03-22 12:30 UTC, mateuszaaa commented on rollup/node/src/chain_spec.rs
> +// ETH Account Info
how about setting initial collators & sudo to `Alith` and `Bobth` that are configured by default in polkadot ui??

2024-03-22 12:53 UTC, iStrike7 commented on rollup/runtime/src/runtime_config.rs
> +					// TODO AccountId20
yes still applies

2024-03-22 23:47 UTC, iStrike7 commented on rollup/node/src/chain_spec.rs
> +// ETH Account Info
Done

2024-03-27 11:06 UTC, merged